name: domhain
channels:
  - defaults
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - conda-forge::r-base=4.1.0
  - bioconda::seqtk=1.3
  - bioconda::cutadapt=2.8
  - bioconda::fasttree=2.1.10
  - bioconda::mafft=7.480
  - bioconda::bioconductor-phyloseq=1.36.0
  - bioconda::bioconductor-microbiome=1.14.0
  - anaconda::pandas=1.3.0
  - anaconda::ipython=7.18.1
  - conda-forge::biopython=1.79
