name: domhain
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::r-base=4.1.0
  - bioconda::seqtk=1.3
  - bioconda::cutadapt=2.8
  - bioconda::fasttree=2.1.10
  - bioconda::mafft=7.480
  - bioconda::bioconductor-phyloseq=1.36.0
  - bioconda::bioconductor-microbiome=1.14.0

