name: 2022-HIV_oral_microbiome
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - anaconda::python=3.7
  - bioconda::cutadapt=3.4
  - bioconda::seqtk=1.3
  - bioconda::kraken2=2.1.2
  - bioconda::mafft=7.490
  - bioconda::fasttree=2.1.10
  - conda-forge::r-base=4.1.0
  - conda-forge::r-stringi=1.7.5
  - conda-forge::r-irkernel=1.3
  - conda-forge::jupyter=1.0.0


