name: 2022-HIV_oral_microbiome
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::r-base=4.1.0
  - bioconda::seqtk=1.3
  - bioconda::cutadapt=2.8
  - conda-forge::r-stringi=1.7.5
  - bioconda::kraken2=2.1.2
  - anaconda::ipython=7.29.0
  - conda-forge::matplotlib=3.5.0
  - conda-forge::biopython=1.79
  - conda-forge::pandas=1.3.4
  - conda-forge::seaborn=0.11.2
